name: Lint

on:
  push:
    branches:
      - "main"
      - "2?R**"
      - "2?.x"
    paths:
      - '**.xlf'
      - '**.4DSettings'
      - '**.4DCatalog'

  pull_request:
    branches:
      - "main"
      - "2?R**"
      - "2?.x"
    paths:
      - '**.xlf'
      - '**.4DSettings'
      - '**.4DCatalog'
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint XML
        run: |
          sudo apt-get install libxml2-utils
          # shellcheck disable=2046
          find . \( -name "*.xlf" -o -name '*.4DCatalog' -o -name "*.4DSettings" \) -type f -exec xmllint --noout '{}' +
