# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Xliff
        run: |
          sudo apt-get install libxml2-utils
          # shellcheck disable=2046
          find . \( -name "*.xlf" -o -name '*.4DCatalog' -o -name "*.4DSettings" \) -type f -exec xmllint --noout '{}' +
